# Generated by Django 3.0.8 on 2020-07-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='photo_main',
            field=models.ImageField(default='', upload_to='photo/%Y/%m/%d/'),
        ),
    ]
