# Generated by Django 3.0.8 on 2020-07-29 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_photo_main'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='is_publishes',
            new_name='is_published',
        ),
    ]
